name: "Coding Standards"

on:
  pull_request:
    paths:
      - composer.*
      - phpcs.xml.dist
      - src/**
      - tests/**
  push:
    paths:
      - composer.*
      - phpcs.xml.dist
      - src/**
      - tests/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.2'

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: "Check coding standards"
        run: "composer run dev:lint:style -- -q --no-colors --report=checkstyle"
